### PR TITLE
Fix for issue #94

### PR DESCRIPTION
**Pull request by shiftylogic**
The hardcoded api version added in the token request is breaking the sample that on the main dev.office.com for Node.js (under some circumstances). I could file an issue against the sample to remove the use of node-adal, or this small change can be applied to fix the main issue.

Hoping this gets pulled into the master library.

### CODE REVIEW

**Comment by weijjia** [comment]
I don't quite understand why the version string could break the request. Do you have a log?

**Comment by shiftylogic** [comment]
Pull down the sample from [OfficeDev Node Sample](https://github.com/OfficeDev/O365-Nodejs-Microsoft-Graph-Connect). Register an app then try to authenticate using your MS Corp credentials.

**Comment by addev-ashish** [comment]
@shiftylogic Can you please redirect this pull request to the dev branch?

**Comment by wharri220** [comment]
I can confirm the api version string is breaking the authorization in places other than the mentioned sample. I have it running against my own Azure resources. It all seems to work correctly, and returns an access token, but the access token is not authorized when requesting the resource. Removing the version string solves it.

**Comment by sameerag** [comment]
Did you get a chance to migrate to [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)? We have a migration guide published [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#what-is-the-status-of-adal-node-is-a-migration-guide-available) which can help you do that.

Since ADAL is reaching end of life, as mentioned in the guidance, we would like to address any applicable issues on msal-node. Please give it a spin and let us know. If you are still seeing this enhancement missing in the new library, please let us know in the msal node repo and we will address it.

**Pull request closed without merging**
