### PR TITLE
Add ability to acquire an on-behalf-of token.  Implements request in Issue #146

### PR DESCRIPTION
**Pull request by ben-m-lucas**
Adds method acquireTokenOnBehalf to AuthenticationContext to support the ability to acquire an on-behalf-of token.

### CODE REVIEW

**Comment by reeceaw** [comment]
@lovemaths Any chance this could be looked over? Very useful feature that no doubt many need, would be great to have this in.

**Comment by jithureddy** [comment]
When this PR will be merged?

**Comment by shani117** [comment]
Can AzureAD comment on the status of this PR? Is there any plans on merging this in OR everyone has to make their own hacks?

**Comment by jasonnutter** [comment]
We are moving the code for ADAL Node to the MSAL.js repo. If you would still like this PR to be considered, please reopen it in the MSAL.js repo: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/adal-node

Futhermore, we highly recommend upgrading to MSAL Node: https://www.npmjs.com/package/@azure/msal-node

**Pull request closed without merging**
