### PR TITLE
fix cache expiry comparison

### PR DESCRIPTION
**Pull request by tripodsan**
isAfter takes a date and not a string.

### CODE REVIEW

**Comment by jasonnutter** [comment]
@tripodsan We are in the process of moving the code for adal-node to the MSAL.js repo, can you please open your PR there? https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/adal-node

**Comment by tripodsan** [comment]
> @tripodsan We are in the process of moving the code for adal-node to the MSAL.js repo, can you please open your PR there? https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/adal-node

sure. can you provide me a link?

**Comment by jasonnutter** [comment]
@tripodsan My reply included a link to the relevant part of the MSAL.js repo.

**Comment by tripodsan** [comment]
done: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3623

**Pull request closed without merging**
